services:
  - type: web
    name: saktris-signaling
    runtime: node
    plan: free
    rootDir: signaling-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
